config/routes.rb
Rails.application.routes.draw do
 	devise_for :users
	root 'home_page#home'

	resources :cities do
  		resources :experiences
  	end

  	
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
	has_many :experiences
	extend FriendlyId
  	friendly_id :name, use: :slugged

	def self.search(search)
		where("name LIKE ?", "%#{search}")
	end
end

app/models/experience.rb
class Experience < ApplicationRecord
  belongs_to :city
  #acts_as_list scope: :city
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
	before_action :authenticate_user!, except: [:index, :show, :search]

	def index
		@cities = City.all
		if params[:search]
			@cities = City.search(params[:search])
			puts "Search carried out"
		else
			@cities = City.all
			puts "Search not carried out"
		end
	end

	def show
		@city = City.friendly.find(params[:id])
		@experiences = Experience.where(city_id: params[:id]).page(params[:page]).per_page(5)
		
	end

	def new
		@city = City.new
	end

	def create
		#render plain: params[:city].inspect
		@city = City.new(city_params)

		@city.save
		redirect_to @city
	end

	private

	def city_params
		params.require(:city).permit(:name, :country, :slug)
	end
end

app/controllers/experiences_controller.rb
class ExperiencesController < ApplicationController
	before_action :authenticate_user!, except: [:index, :show]
	
	def index
		@experiences = Experience.all
	end
	
	def create
		@city = City.friendly.find(params[:city_id])
		@experience = @city.experiences.create(experience_params)
		redirect_to city_path(@city)
	end

	def show
		@city = City.friendly.find(params[:id])
		@experience = @city.experiences.find(experience_params)
	end

	private

	def experience_params
		params.require(:experience).permit(:title, :description)
	end

end

app/controllers/home_page_controller.rb
class HomePageController < ApplicationController
  def home
  	@cities = City.all
		if params[:search]
			@cities = City.search(params[:search])
			puts "Search carried out"
		else
			@cities = City.all
			puts "Search not carried out"
		end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/experiences_helper.rb
module ExperiencesHelper
end

app/helpers/home_page_helper.rb
module HomePageHelper
end

app/views/cities/delete.html.erb
<div>
	<h2>Delete Cities</h2>

	<%= form_for(@city, :url => city_path(@city)), :method => 'delete' do |f| %>
		<p>Are you sure you permanently want to delete this city?</p>
		<p><%= f.object.name %></p>
		<%= f.submit("Delete City") %>
	<% end %>
</div>

app/views/cities/index.html.erb
<div class="text-center">
	<% if @cities.present? %>
		<% render @cities %>
		<% puts "rendered cities" %>
	<% else %>
		<p><%= params[:search] %> was not found.</p>
		<p>We don't have elastic search yet so we have some trouble with misspelling.</p>
		<p>Please check the spelling of your search term or have a look at our list of cities.</p>
		<%= link_to "Cities List", '/cities' %>
	<% end %>
</div>
<div class="container-fluid text-center">
	
	<% puts "doing list" %>
	<% if params[:search] %>
		<% puts "#{params[:search]}" %>
		<% @cities.each do |city| %>
			<h3><%= city.name %></h3>
			<p><%= city.country %></p>
			<%= link_to "See More", city_path(city) %>
		<% end %>
	<% else %>
		<table>
		<% @cities.in_groups_of(3) do |row_cities| %>
			<tr>	
				<% row_cities.each do |city| %>		
					<td>
						<h3><%= city.name %></h3>
						<p><%= city.country %></p>
						<%= link_to "See More", city_path(city) %>
					</td>
				<% end %>
			</tr>
		<% end %>
		</table>
	<% end %>
</div>

app/views/cities/new.html.erb
<h1 class="text-center">Add City</h1>
<p class="text-center">Cities cannot be added at this time</p>
<!--
<div class="text-center">
#	<%= form_for :city, url: cities_path do |f| %>
#		<p>
#			<%= f.label :name %><br>
#			<%= f.text_field :name %>
#		</p>
#
#		<p>
#			<%= f.label :country %><br>
#			<%= f.text_field :country %>
#		</p>
#
#		<p>
#			<%= f.submit %>
#		</p>
#	<% end %>
</div>
<br>
<div class="text-center">
	<%= link_to "Back", "/" %>
</div>
-->

app/views/cities/show.html.erb
<div class="container-fluid text-center" id="city_style">
	<h2><%= @city.name %></h2>
    <small class="text-muted"><%= @city.country %></small>
    <br>
	<a href="#" type="button" data-toggle="modal" data-target="#experience_modal">Post an Experience</a>
            <div class="modal fade" id="experience_modal">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title">Post an Experience</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <%= form_for([@city, @city.experiences.build]) do |f| %>
                                <div class="form-group row">
                                    <%= f.label :title, :class => "col-3 col-form-label" %></label>
                                    <div class="col-9">
                                        <%= f.text_field :title, :id => "exp-title-input", :required => true %>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <%= f.label :description, :class => "col-3 col-form-label" %>
                                    <div class="col-9">
                                        <%= f.text_field :description, :id => "exp-desc-input", :required => true %>
                                    </div>
                                </div>
                                <div class="form-group text-center">
                                    <%= f.submit 'Post Experience', :class => "btn post_exp_submit" %>
                                </div>

                                <!--
                                <div class="form-group row offset-3">
                                	<div class="form-check form-check-inline">
  										<label class="form-check-label col-3">
    										<input class="form-check-input" type="checkbox" id="inlineCheckbox1" value="option1"><i class="fa fa-cutlery" aria-hidden="true"></i>
  										</label>
									</div>
									<div class="form-check form-check-inline">
  										<label class="form-check-label col-3">
    										<input class="form-check-input" type="checkbox" id="inlineCheckbox2" value="option2"><i class="fa fa-tree" aria-hidden="true"></i>
  										</label>
									</div>
									<div class="form-check form-check-inline">
  										<label class="form-check-label col-3">
    										<input class="form-check-input" type="checkbox" id="inlineCheckbox3" value="option3"><i class="fa fa-glass" aria-hidden="true"></i>
  										</label>
									</div>
									<div class="form-check form-check-inline">
  										<label class="form-check-label col-3">
    										<input class="form-check-input" type="checkbox" id="inlineCheckbox4" value="option4"><i class="fa fa-camera" aria-hidden="true"></i>
  										</label>
									</div>
                                </div>
                                -->
                            <% end %>
                        </div>
                    </div>
                </div>
            </div>
</div>

<hr id="hr_style">


<div class="container-fluid">
    <% if Experience.where(city_id: @city.id).blank? %>
        <div class="text-center" id="no_exp">
            <p>There are no experiences yet. Be the first to post one!</p>
        </div>
    <% else %>
        <% @city.experiences.order('votes desc').each do |experience| %>
            
            <div class="row text-center" id="experience_block">
                <div class="col-1">
                    <div class="row" id="row_1">
                        <div class="col-6" id="rank_style">
                            <p><%= experience.id %></p>
                            
                        </div>
                        <div class="col-6" id="counter_style">
                            <% if experience.votes.blank? %>

                            <% else %>
                                <i class="fa fa-arrow-up" aria-hidden="true"></i>
                                <div>
                                    <p id="counter_number"><%= experience.votes %></p>
                                </div>
                                <i class="fa fa-arrow-down" aria-hidden="true"></i>
                            <% end %>
                        </div>
                    </div>
                </div>
                <div class="col-10" id="experience_words">
                    <p class="text-left" id="experience_title_style"><%= experience.title %></p>
                    <p class="text-left" id="experience_desc_style" maxlength="50"><%= experience.description %></p>
                </div>
                <div class="col-1" id="category_style">
                    <!--<i class="fa fa-cutlery fa-3x" aria-hidden="true"></i>-->
                    <%= experience.category %>
                </div>
            </div>
        <% end %>
            
    <% end %>
</div>

app/views/experiences/show.html.erb
<h1>Here is the experience</h1>

<%= @experience %>

app/views/home_page/home.html.erb
<div class="container-fluid text-center">
	<p>Welcome intrepid adventurer to explorecities.io! Ever feel bored in your own home city? Ever get some new place and find absolutely nothing to do on Trip Advisor and so on? Maybe you want to avoid the tourist traps this time. Never fear my friends! This is a project where people around the world share cool Experiences in cities around the world. To see the full potential of this project have a look at <%= link_to "Brisbane", '/cities/brisbane' %>, the developer's Home City. The world is beautiful and full of wonder, let's start sharing!
    </p>
    <p>
    Test Account: user@user.com
    Password: password
    </p>

</div>
<div class="container-fluid text-center">
    <table>
    <% @cities.in_groups_of(3,false) do |row_cities| %>
        <tr>    
            <% row_cities.each_with_index do |city,index| %>
                <td>
                    <h3><%= city.name %></h3>
                    <p><%= city.country %></p>
                    <%= link_to "See More", city_path(city) %>
                </td>
            <% end %>
        </tr>
    <% end %>
    </table>
</div>

app/views/layouts/_bootstrap.html.erb
<script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>

app/views/layouts/_footer.html.erb
<footer class="footer navbar navbar-fixed-bottom navbar-inverse bg-black" id="footer_style">
    <div>
    <p class="navbar-brand pull-left" id="copyright">&copy;2017 <a href="https://twitter.com/santiagochamon" target="_blank">@santiagochamon </a></p>
    
    
    <ul class="navbar-nav ml-auto pull-right">
        <li class="nav-item active">
            <a class="nav-link" href="#" type="button" data-toggle="modal" data-target="#contact_modal">Contact</a>
            <div class="modal fade" id="contact_modal">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title">Contact</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <p>Woah! Hey there Friend!</p>
                            <p>Want to contact me directly?</p>
                            <p>You can reach me super duper quick on <a href="https://twitter.com/santiagochamon">Twitter</a>!</p>
                            <p>Or send me an email:</p>
                            <p>santiago.chamon@gmail.com</p>
                        </div>
                    </div>
                </div>
            </div>
        </li>
    </ul>
    </div>
</footer>

app/views/layouts/_header.html.erb
<header class="jumbotron text-center rounded-0" id="header_jumbotron">
	<div id="header_text">
		<h3>What City would you like to explore today?</h3>
		
		<!-- <input type="string" name="search" id="input"> -->
		<%= form_tag(cities_path, :method => "get", id: "search-form") do %>
			<i class="fa fa-search fa-2x" aria-hidden="true" id="looking-glass"></i>
			<%= text_field_tag :search, params[:search], placeholder: "Search Cities", :id => 'input', :required => true %>
			<%= submit_tag "Go", :id => 'input_button' %>
		<% end %>
	</div>
</header>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-toggleable-md navbar-inverse bg-black" id="nav_style">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation" id="toggler_style">
    <span class="navbar-toggler-icon" id="toggler_icon_style"></span>
  </button>
  <a class="navbar-brand" href="/">explorecities.io</a>

	<div class="collapse navbar-collapse" id="navbarSupportedContent">
    <div class="navbar-nav ml-auto">
      <a class="nav-link active" href="/users/sign_in" type="button">Login <span class="sr-only">(current)</span></a>
      <li class="nav-item active">
        <a class="nav-link" href="/users/sign_up" type="button">Signup</a>
      </li>
    </div>
  </div>
</nav>

app/views/layouts/_pagination.html.erb
<div class="container-fluid text-center" id="pagination_style">
	<span class="previous_page disabled">Previous </span>
	<em class="current">1 </em>
	<a href="#" rel="next">2 </a>
	<a href="#" class="next_page">Next</a>
</div>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

<script src="https://use.fontawesome.com/aaf8808239.js"></script>
<link href="https://fonts.googleapis.com/css?family=Permanent+Marker" rel="stylesheet">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
<link href="bootstrap-social.css" rel="stylesheet">

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ExploreCities.io</title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device=width, initial-scale=1">
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= render 'layouts/nav' %>
    
    <div class="container-fluid text-center">
      <% if notice %>
        <p class="notice" id="flash_notice"><%= notice %></p>
      <% elsif alert %>
        <p class="alert" id="flash_notice"><%= alert %></p>
      <% end %>
    </div>

    <div>
      <%= yield %>  
    </div>
    
    <%= render 'layouts/footer' %>
    <%= render 'layouts/bootstrap' %>
  </body>
</html>